### ISSUE TITLE
iTerm2 Support

### ISSUE THREAD

**Issue by j-manu** [jeffkreeftmeijer/wwdc16.terminal#1]
1. Can you provide an iTerm2 profile?
2. What is the font used in the screenshots?

**Comment by jeffkreeftmeijer** [comment]
I'm working on a tool to turn a list of colors into colorschemes for Terminal.app and iTerm2. I'll add an iTerm2 color scheme when that's done, and I'll use this issue to keep you posted. 

UPDATE: @effkay already made an iTerm2 version: https://github.com/effkay/iTerm-wwdc16

The typeface used in the screenshots is SF Mono, the font used on http://apple.com/wwdc.

**Comment by j-manu** [comment]
Thank you!

**Comment by jeffkreeftmeijer** [comment]
I just added iTerm2 support to [Colorscheme](https://github.com/jeffkreeftmeijer/colorscheme) and started using it for wwdc16.terminal to generate themes for both Terminal.app and iTerm2. 🎉

If you have time, please try it out and open a new issue if you run into any problems. I'm closing this one.
